/**
 * SendX REST API
 * # Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendx.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ReportData from '../model/ReportData';

/**
* Reports service.
* @module sendx/api/ReportsApi
* @version 1.0.0
*/
export default class ReportsApi {

    /**
    * Constructs a new ReportsApi. 
    * @alias module:sendx/api/ReportsApi
    * @class
    * @param {module:sendx/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:sendx/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get CampaignReport Data
     * Retrieve the campaign report data based on the provided campaign id.
     * @param {String} campaignId The ID of the campaign to retrieve the report data for
     * @param {Object} opts Optional parameters
     * @param {String} [integrationType] Type of integration for the report data (optional)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:sendx/model/ReportData} and HTTP response
     */
    getCampaignReportWithHttpInfo(campaignId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'campaignId' is set
      if (campaignId === undefined || campaignId === null) {
        throw new Error("Missing the required parameter 'campaignId' when calling getCampaignReport");
      }

      let pathParams = {
        'campaignId': campaignId
      };
      let queryParams = {
        'integrationType': opts['integrationType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ReportData;
      return this.apiClient.callApi(
        '/report/campaign/{campaignId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get CampaignReport Data
     * Retrieve the campaign report data based on the provided campaign id.
     * @param {String} campaignId The ID of the campaign to retrieve the report data for
     * @param {Object} opts Optional parameters
     * @param {String} opts.integrationType Type of integration for the report data (optional)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:sendx/model/ReportData}
     */
    getCampaignReport(campaignId, opts) {
      return this.getCampaignReportWithHttpInfo(campaignId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
