/**
 * SendX REST API
 * # Introduction The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendx.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/sendx/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/sendx/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.sendx);
  }
}(this, function(expect, sendx) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new sendx.ListModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListModel', function() {
    it('should create an instance of ListModel', function() {
      // uncomment below and update the code to test ListModel
      //var instance = new sendx.ListModel();
      //expect(instance).to.be.a(sendx.ListModel);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property sendThankYouMail (base name: "sendThankYouMail")', function() {
      // uncomment below and update the code to test the property sendThankYouMail
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property thankYouFromName (base name: "thankYouFromName")', function() {
      // uncomment below and update the code to test the property thankYouFromName
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property thankYouFromEmail (base name: "thankYouFromEmail")', function() {
      // uncomment below and update the code to test the property thankYouFromEmail
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property thankYouMailSubject (base name: "thankYouMailSubject")', function() {
      // uncomment below and update the code to test the property thankYouMailSubject
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property thankYouMailMessage (base name: "thankYouMailMessage")', function() {
      // uncomment below and update the code to test the property thankYouMailMessage
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property thankYouSender (base name: "thankYouSender")', function() {
      // uncomment below and update the code to test the property thankYouSender
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property confirmFromName (base name: "confirmFromName")', function() {
      // uncomment below and update the code to test the property confirmFromName
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property confirmFromEmail (base name: "confirmFromEmail")', function() {
      // uncomment below and update the code to test the property confirmFromEmail
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property confirmMailSubject (base name: "confirmMailSubject")', function() {
      // uncomment below and update the code to test the property confirmMailSubject
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property confirmMailMessage (base name: "confirmMailMessage")', function() {
      // uncomment below and update the code to test the property confirmMailMessage
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property confirmSuccessPage (base name: "confirmSuccessPage")', function() {
      // uncomment below and update the code to test the property confirmSuccessPage
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property updated (base name: "updated")', function() {
      // uncomment below and update the code to test the property updated
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

    it('should have the property confirmSender (base name: "confirmSender")', function() {
      // uncomment below and update the code to test the property confirmSender
      //var instance = new sendx.ListModel();
      //expect(instance).to.be();
    });

  });

}));
